version: '2'
services:
    cookapp-mysql:
        container_name: cookapp-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/cookApp/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=cookapp
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
